src/Entity/Article.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use App\Repository\ArticleRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2, max: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 150)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:5, max: 150)]
    private ?string $description = null;

    #[ORM\Column(length: 500)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2, max: 500)]
    private ?string $texte = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->category = new ArrayCollection();
    }

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $auteur = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToOne(targetEntity:User::class, inversedBy: 'articles')]
    private $user;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'articles')]
    private Collection $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }


}

src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $Categorie = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->articles = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->Categorie;
    }

    #[ORM\Column(length: 50)]
    private ?string $auteur = null;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    private ?user $user = null;

    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'category')]
    private Collection $articles;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            $article->removeCategory($this);
        }

        return $this;
    }

}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use App\Repository\CategoryRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('texte')
            // ->add('auteur')
            ->add('image')
            ->add('category')
            // ->add('category',EntityType::class,
            // [
            //     'class'=>Category::class,
            //     'query_builder' => function (CategoryRepository $category){
            //         return $category -> createQueryBuilder('i');
            //     }
            // ]
            // )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;


use App\Entity\Article;
use App\Form\ArticleType;

use App\Repository\ArticleRepository;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * This controller display how to create an article
     *
     * @param Request $request
     * @param ArticleRepository $articleRepository
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, ArticleRepository $articleRepository,
     EntityManagerInterface $manager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $article = $form->getData();

            $article->setUser($this->getUser());
            
            $articleRepository->save($article, true);

            // $manager->persist($article);
            // $manager->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    #[Security("is_granted('ROLE_USER') and user === article.getUser()")]
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->save($article, true);

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}


{{ form_start(form) }}
    <div class="block-complet">
        <div class="block_complet_modifier">
            <div class="titre_article_modif">
                <h2>Création d'un article</h2>
                <div class="categorie_choix">
                    <p>Catégorie:</p>

                    <div class="select_categorie">
                        {# <select name="catégorie" id="pet-select">
                            <option value="">--Choisissez une catégorie--</option>
                            <option value="">Dog</option>
                        </select> #}
                        {{ form_widget(form.category,{'attr':{'class':'input_modif_choix_categorie'}}) }}
                    </div>
                </div>
            </div>
            <div class="hr_modif_article">
                <hr>
            </div>
            <div class="choix_titre">
                <h3>Titre</h3>
                <hr>
                {{ form_widget(form.name,{'attr':{'class':'input_modif_titre_article'}}) }}
            </div>
            <div class="choix_description">
                <h3>Description</h3>
                <hr>
                {{ form_widget(form.description,{'attr':{'class':'input_modif_desciption_article'}}) }}
            </div>
            <div class="choix_texte">
                <h3>Ajouter du texte à votre publication</h3>
                <hr>
                {{ form_widget(form.texte,{'attr':{'class':'input_modif_texte_article'}}) }}
            </div>
            <div class="choix_image">
                <h3>Vous pouvez illustrer votre publication</h3>
                <hr>
                {{ form_widget(form.image,{'attr':{'class':'input_modif_image_article'}}) }}
                
                
                {# {{ form_widget(form.name,,{'attr':{'class':'input_modif_image_article'}}) }} #}
            </div>
        </div>
        <div class="block_btn_sauvegarder">
            <button class="btn btn_save_article">{{ button_label|default('Nouvel article') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/article/_form.modifier.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}


{{ form_start(form) }}
    <div class="block-complet">
        <div class="block_complet_modifier">
            <div class="titre_article_modif">
                <h2>Modification de l'article #{{ article.id }} - {{ article.name }}</h2>
                <div class="categorie_choix">
                    <p>Catégorie:</p>
                    <div class="select_categorie">
                        {# <select name="catégorie" id="pet-select">
                            <option value="">--Choisissez une catégorie--</option>
                            <option value="">Dog</option>
                        </select> #}
                        {{ form_widget(form.category,{'attr':{'class':'input_modif_categorie_article'}}) }}
                    </div>
                </div>
            </div>
            <div class="hr_modif_article">
                <hr>
            </div>
            <div class="choix_titre">
                <h3>Titre</h3>
                <hr>
                {{ form_widget(form.name,{'attr':{'class':'input_modif_titre_article'}}) }}
            </div>
            <div class="choix_description">
                <h3>Description</h3>
                <hr>
                {{ form_widget(form.description,{'attr':{'class':'input_modif_desciption_article'}}) }}
            </div>
            <div class="choix_texte">
                <h3>Ajouter du texte à votre publication</h3>
                <hr>
                {{ form_widget(form.texte,{'attr':{'class':'input_modif_texte_article'}}) }}
            </div>
            <div class="choix_image">
                <h3>Vous pouvez illustrer votre publication</h3>
                <hr>
                {{ form_widget(form.image,{'attr':{'class':'input_modif_image_article'}}) }}
                
                {# {{ form_widget(form.name,,{'attr':{'class':'input_modif_image_article'}}) }} #}
            </div>
        </div>
        <div class="block_btn_sauvegarder">
            <button class="btn btn_save_article">{{ button_label|default('Save') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}

    {{ include('article/_form.modifier.html.twig', {'button_label': 'Sauvegarder'}) }}

    <a href="{{ path('article_index') }}">retourner à la page de blog</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index
{% endblock %}

{% block body %}


	<div class="block-complet">
		<div class="block_blog">
			<div class="titre_blog">
				<h2>Blog</h2>
			</div>
			<div class="hr_blog">
				<hr>
			</div>
			<div class="articles_blog">
				{% for article in articles %}
					<div class="block_article_blog">
						<div class="block_gauche_blog">
							<div class="titre_article_blog">
								<h3>{{ article.name }}</h3>
								<p>par {{article.user.name}}
									{{ article.auteur }}</p>
							</div>
							<div class="hr_article_blog">
								<hr>
							</div>
							<div class="info_article_blog">
								<p class='date_publication'>Edité le
									{{ article.createdAt ? article.createdAt|date('d-m-Y') : '' }}</p>
								{# <p class="categorie_article">Catégorie : #}
									{# {{ article.category.categorie }}</p> #}
							</div>
							<div class="titre_description">
								<h3>Description</h3>
							</div>
							<div class="texte_description">
								<p>{{ article.description }}</p>
							</div>
						</div>
						{% if app.user and app.user == article.user %}
							<div class="block_droit_blog">
								<a href="{{ path('app_article_show', {'id': article.id}) }}" class='bouton_voir_blog'>Voir la publication</a>

								<a href="{{ path('app_article_edit', {'id': article.id}) }}" class="bouton_modifier_blog">Modifier</a>
							</div>
						{% else %}
							<div class="block_droit_blog">
								<a href="{{ path('app_article_show', {'id': article.id}) }}" class='bouton_voir_blog'>Voir la publication</a>
							</div>
						{% endif %}
					</div>


				{% else %}
					<tr>
						<td colspan="9">no records found</td>
					</tr>
				{% endfor %}

			</div>
		</div>
		<div class="block_btn_new_article">
			<div class="block_a_new_article">
				<a href="{{ path('app_article_new') }}" class="btn_new_article">Créer un Nouvel Article</a>
			</div>
		</div>
	</div>
	{# <div class="block-complet"> <div class="block_blog">
																			<div class="titre_blog">
																				<h2>Blog</h2>
																			</div>
																			<div class="hr_blog">
																				<hr>
																			</div>
																			<div class="articles_blog">
																				{% for article in articles %}
																					<div class="block_article_blog">
																						<div class="block_gauche_blog">
																							<div class="titre_article_blog">
																								<h3>{{ article.name }}</h3>
																								<p>par
																									{{ article.auteur }}</p>
																							</div>
																							<div class="hr_article_blog">
																								<hr>
																							</div>
																							<div class="info_article_blog">
																								<p class='date_publication'>Edité le
																									{{ article.createdAt ? article.createdAt|date('d-m-Y') : '' }}</p>
																								<p class="categorie_article">Catégorie :
																									{{ article.categorie }}</p>
																							</div>
																							<div class="titre_description">
																								<h3>Description</h3>
																							</div>
																							<div class="texte_description">
																								<p>{{ article.description }}</p>
																							</div>
																						</div>
																						<div class="block_droit_blog">
																							<a href="{{ path('app_article_show', {'id': article.id}) }}" class='bouton_voir_blog'>Voir la publication</a>
																							<a href="{{ path('app_article_edit', {'id': article.id}) }}" class="bouton_modifier_blog">Modifier</a>
																						</div>
																					</div>
																
																
																				{% else %}
																					<tr>
																						<td colspan="9">no records found</td>
																					</tr>
																				{% endfor %} #}
<a href="{{ path('app_article_new') }}">Create new</a>
	
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}


    

<div class="block-complet">
    <div class="container block-article">
        <div class="titre-categorie">
            <h1>{{ article.name }}</h1>
            {# <p>catégorie : {{ article.category.categorie }}</p> #}
        </div>
        <div class="hr">
            <hr>
        </div>
        <div class="article">
            <div class="block-text">
                {{ article.texte }}
            </div>
                <hr>
            <div class="block-image">
                <img src="{{ article.image }}" alt="">
                <p>Publié par {{ article.auteur }}</p>
                <p>Edité le {{ article.createdAt ? article.createdAt|date('d-m-Y') : '' }}</p>
            </div>
        </div>
    </div>
    <div class="block_commentaires_btn_article">
        {% if app.user %}
            <div class="commentaire_btn_article">
                <a href="{{path('app_commentaire_show', { 'id' : article.id})}}">Commentaires</a>
                <a href="{{path('app_commentaire_new', {'id': article.id})}}" class='btn_commentaire'> Ajouter un commentaire </a>
                {# <button class="btn_commentaire">Ajouter un commentaire</button>  #}
            </div>
        {% else %}
            <div class="commentaire_btn_article">
                <a href="">Commentaires</a>
            </div>

        {% endif %}
    </div>
</div>
    

    {# <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ article.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Texte</th>
                <td>{{ article.texte }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ article.createdAt ? article.createdAt|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ article.categorie }}</td>
            </tr>
            <tr>
                <th>Auteur</th>
                <td>{{ article.auteur }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ article.image }}</td>
            </tr>
        </tbody>
    </table> #}

    {# <a href="{{ path('article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }} #}
{% endblock %}